/*
Copyright 2019 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	internalsv1alpha1 "github.com/rccrdpccl/bindings/pkg/apis/internals/v1alpha1"
	versioned "github.com/rccrdpccl/bindings/pkg/client/clientset/versioned"
	internalinterfaces "github.com/rccrdpccl/bindings/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/rccrdpccl/bindings/pkg/client/listers/internals/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PodSelectorInformer provides access to a shared informer and lister for
// PodSelectors.
type PodSelectorInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.PodSelectorLister
}

type podSelectorInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPodSelectorInformer constructs a new informer for PodSelector type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPodSelectorInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPodSelectorInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPodSelectorInformer constructs a new informer for PodSelector type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPodSelectorInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.InternalsV1alpha1().PodSelectors(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.InternalsV1alpha1().PodSelectors(namespace).Watch(context.TODO(), options)
			},
		},
		&internalsv1alpha1.PodSelector{},
		resyncPeriod,
		indexers,
	)
}

func (f *podSelectorInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPodSelectorInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *podSelectorInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&internalsv1alpha1.PodSelector{}, f.defaultInformer)
}

func (f *podSelectorInformer) Lister() v1alpha1.PodSelectorLister {
	return v1alpha1.NewPodSelectorLister(f.Informer().GetIndexer())
}
