/*
Copyright 2019 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/rccrdpccl/bindings/pkg/apis/bindings/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVPABindings implements VPABindingInterface
type FakeVPABindings struct {
	Fake *FakeBindingsV1alpha1
	ns   string
}

var vpabindingsResource = schema.GroupVersionResource{Group: "bindings.rccrdpccl.dev", Version: "v1alpha1", Resource: "vpabindings"}

var vpabindingsKind = schema.GroupVersionKind{Group: "bindings.rccrdpccl.dev", Version: "v1alpha1", Kind: "VPABinding"}

// Get takes name of the vPABinding, and returns the corresponding vPABinding object, and an error if there is any.
func (c *FakeVPABindings) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VPABinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(vpabindingsResource, c.ns, name), &v1alpha1.VPABinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VPABinding), err
}

// List takes label and field selectors, and returns the list of VPABindings that match those selectors.
func (c *FakeVPABindings) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VPABindingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(vpabindingsResource, vpabindingsKind, c.ns, opts), &v1alpha1.VPABindingList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VPABindingList{ListMeta: obj.(*v1alpha1.VPABindingList).ListMeta}
	for _, item := range obj.(*v1alpha1.VPABindingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested vPABindings.
func (c *FakeVPABindings) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(vpabindingsResource, c.ns, opts))

}

// Create takes the representation of a vPABinding and creates it.  Returns the server's representation of the vPABinding, and an error, if there is any.
func (c *FakeVPABindings) Create(ctx context.Context, vPABinding *v1alpha1.VPABinding, opts v1.CreateOptions) (result *v1alpha1.VPABinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(vpabindingsResource, c.ns, vPABinding), &v1alpha1.VPABinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VPABinding), err
}

// Update takes the representation of a vPABinding and updates it. Returns the server's representation of the vPABinding, and an error, if there is any.
func (c *FakeVPABindings) Update(ctx context.Context, vPABinding *v1alpha1.VPABinding, opts v1.UpdateOptions) (result *v1alpha1.VPABinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(vpabindingsResource, c.ns, vPABinding), &v1alpha1.VPABinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VPABinding), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVPABindings) UpdateStatus(ctx context.Context, vPABinding *v1alpha1.VPABinding, opts v1.UpdateOptions) (*v1alpha1.VPABinding, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(vpabindingsResource, "status", c.ns, vPABinding), &v1alpha1.VPABinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VPABinding), err
}

// Delete takes name of the vPABinding and deletes it. Returns an error if one occurs.
func (c *FakeVPABindings) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(vpabindingsResource, c.ns, name), &v1alpha1.VPABinding{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVPABindings) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(vpabindingsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.VPABindingList{})
	return err
}

// Patch applies the patch and returns the patched vPABinding.
func (c *FakeVPABindings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VPABinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(vpabindingsResource, c.ns, name, pt, data, subresources...), &v1alpha1.VPABinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VPABinding), err
}
