# Copyright 2019 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: defaulting.webhook.bindings.rccrdpccl.dev
  labels:
    bindings.rccrdpccl.dev/release: devel
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook
      namespace: binding-system
  failurePolicy: Fail
  name: defaulting.webhook.bindings.rccrdpccl.dev
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation.webhook.bindings.rccrdpccl.dev
  labels:
    bindings.rccrdpccl.dev/release: devel
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook
      namespace: binding-system
  failurePolicy: Fail
  name: validation.webhook.bindings.rccrdpccl.dev
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: config.webhook.bindings.rccrdpccl.dev
  labels:
    bindings.rccrdpccl.dev/release: devel
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook
      namespace: binding-system
  failurePolicy: Fail
  name: config.webhook.bindings.rccrdpccl.dev
  namespaceSelector:
    matchExpressions:
    - key: bindings.rccrdpccl.dev/release
      operator: Exists
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: vpabindings.webhook.bindings.rccrdpccl.dev
  labels:
    bindings.rccrdpccl.dev/release: devel
webhooks:
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      service:
        name: webhook
        namespace: binding-system
    failurePolicy: Fail
    name: vpabindings.webhook.bindings.rccrdpccl.dev
---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-certs
  namespace: binding-system
  labels:
    bindings.rccrdpccl.dev/release: devel
# The data is populated at install time.
